In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import seaborn as sn

In [36]:
df=pd.read_csv('Movie_collection.csv')

In [54]:
df.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Avg_age_actors  Num_multiplex  \
0            7.910            7.995  ...              23            494   
1            7.440            7.470  ...              42            462   
2            7.495            7.515  ...              38            458   
3            6.920            7.020  ...              45            472   
4            6.815            7.070  ...              55            395   

   Start_Tech_Oscar  3D_available_NO  3D_available_YES  Genre_Action  \
0                 0                0                 1             0   
1                 1                1                 0             0   
2                 0                1                 0             0   
3                 0                0                 1             0   
4                 0                1                 0             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0             0            0               1                    1  
1             0            1               0                    1  
2             1            0               0                    1  
3             0            1               0                    1  
4             0            1               0                    1  

[5 rows x 24 columns]

In [7]:
#Training logistic model

In [111]:
x=df.loc[:,df.columns!='Start_Tech_Oscar'] #Independent variable

In [112]:
y=df['Start_Tech_Oscar'] #dependent variable

In [113]:
x.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Twitter_hastags  Avg_age_actors  \
0            7.910            7.995  ...          223.840              23   
1            7.440            7.470  ...          243.456              42   
2            7.495            7.515  ...         2022.400              38   
3            6.920            7.020  ...          225.344              45   
4            6.815            7.070  ...          225.792              55   

   Num_multiplex  3D_available_NO  3D_available_YES  Genre_Action  \
0            494                0                 1             0   
1            462                1                 0             0   
2            458                1                 0             0   
3            472                0                 1             0   
4            395                1                 0             0   

   Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0             0            0               1                    1  
1             0            1               0                    1  
2             1            0               0                    1  
3             0            1               0                    1  
4             0            1               0                    1  

[5 rows x 23 columns]

In [114]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Start_Tech_Oscar, dtype: int64

In [120]:
df=pd.get_dummies(df) #converts series of strings to dummy codes
df.info() #provides the information about the dataset
df.Time_taken=df.Time_taken.fillna(df.Time_taken.mean()) #fill the missing values by replacing mean
df.fillna(0) #fill the NaN values with 0

In [121]:
#Use Logistic regression model to predict

In [117]:
from sklearn.linear_model import LogisticRegression

In [118]:
cls_rgs=LogisticRegression()  #Create classification object

In [19]:
#Fit the trained data

In [119]:
cls_rgs.fit(x,y)

E:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# coefficients

In [122]:
cls_rgs.coef_ #β0

array([[-6.01467684e-05,  1.04511479e-04, -1.10593955e-03,
        -1.79854873e-05,  5.40113809e-05, -2.15871819e-03,
         2.02158402e-05,  2.55123818e-05,  2.38294723e-05,
         3.08217084e-05, -9.74690209e-05,  8.32503429e-06,
         9.57008329e-04, -9.25685031e-03, -1.71785370e-03,
        -8.92534235e-04,  1.79669542e-05, -4.09938609e-05,
        -1.06927831e-05, -2.67783785e-05, -3.57822802e-05,
         5.02265350e-05, -2.30269067e-05]])

In [123]:
cls_rgs.intercept_ #β1

array([-2.30269349e-05])

In [124]:
#use add_constant

In [125]:
import statsmodels.api as sn

In [128]:
x_const=sn.add_constant(x) #By default, statsmodels fits a line passing through the origin,
                           #i.e. it doesn't fit an intercept. Hence, you need to use the command 'add_constant'
                           #so that it also fits an intercept.

In [127]:
x_const

Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0    36524.125         138.7               7.825                8.095   
1    35668.655         152.4               7.505                7.650   
2    39912.675         134.6               7.485                7.570   
3    38873.890         119.3               6.895                7.035   
4    39701.585         127.7               6.920                7.070   
..         ...           ...                 ...                  ...   
501  36624.115         142.6               8.680                8.775   
502  33996.600         150.2               8.780                8.945   
503  38751.680         164.5               8.830                8.970   
504  37740.670         162.8               8.730                8.845   
505  33496.650         154.3               8.640                8.880   

     Director_rating  Producer_rating  ...  Twitter_hastags  Avg_age_actors  \
0              7.910            7.995  ...          223.840              23   
1              7.440            7.470  ...          243.456              42   
2              7.495            7.515  ...         2022.400              38   
3              6.920            7.020  ...          225.344              45   
4              6.815            7.070  ...          225.792              55   
..               ...              ...  ...              ...             ...   
501            8.620            8.970  ...          243.584              27   
502            8.770            8.930  ...          263.296              20   
503            8.855            9.010  ...          243.824              31   
504            8.800            8.845  ...          303.520              47   
505            8.680            8.790  ...          203.040              45   

     Num_multiplex  3D_available_NO  3D_available_YES  Genre_Action  \
0              494                0                 1             0   
1              462                1                 0             0   
2              458                1                 0             0   
3              472                0                 1             0   
4              395                1                 0             0   
..             ...              ...               ...           ...   
501            561                1                 0             1   
502            600                0                 1             1   
503            576                1                 0             0   
504            607                0                 1             0   
505            604                0                 1             0   

     Genre_Comedy  Genre_Drama  Genre_Thriller  MPAA_film_rating_PG  
0               0            0               1                    1  
1               0            1               0                    1  
2               1            0               0                    1  
3               0            1               0                    1  
4               0            1         

In [129]:
# building the model and fitting the data

In [130]:
import statsmodels.discrete.discrete_model as sm

In [131]:
logit=sm.Logit(y,x_const).fit()

Optimization terminated successfully.
         Current function value: 0.581579
         Iterations 20


In [135]:
#In the output, ‘Iterations‘ refer to the number of times the model iterates over the data, trying to optimize the model. By default, the maximum number of iterations performed is 58, after which the optimization fails

In [136]:
logit.summary() #The summary table below gives us a descriptive summary about the regression results.

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:       Start_Tech_Oscar   No. Observations:                  506
Model:                          Logit   Df Residuals:                      485
Method:                           MLE   Df Model:                           20
Date:                Thu, 27 Apr 2023   Pseudo R-squ.:                  0.1559
Time:                        13:31:52   Log-Likelihood:                -294.28
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 3.360e-14
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Collection             -0.0001   1.42e-05     -7.340      0.000      -0.000   -7.66e-05
Marketing expense      -0.0007      0.001     -1.016      0.310      -0.002       0.001
Production expense     -0.0045      0.013     -0.353      0.724      -0.030       0.021
Multiplex coverage      4.9238      2.576      1.912      0.056      -0.124       9.972
Budget                  0.0002   4.83e-05      3.823      0.000       9e-05       0.000
Movie_length           -0.0058      0.006     -0.920      0.358      -0.018       0.007
Lead_ Actor_Rating     -2.0478      1.676     -1.222      0.222      -5.333       1.238
Lead_Actress_rating     2.5189      1.794      1.404      0.160      -0.998       6.035
Director_rating        -1.8018      1.744     -1.033      0.301      -5.220       1.616
Producer_rating         2.0443      0.960      2.130      0.033       0.163       3.926
Critic_rating           0.3868      0.169      2.289      0.022       0.056       0.718
Trailer_views        1.502e-05   2.99e-06      5.028      0.000    9.16e-06    2.09e-05
Time_taken              0.0075      0.003      2.225      0.026       0.001       0.014
Twitter_hastags        -0.0028      0.002     -1.163      0.245      -0.007       0.002
Avg_age_actors         -0.0038      0.008     -0.467      0.641      -0.020       0.012
Num_multiplex           0.0025      0.002      1.057      0.290      -0.002       0.007
3D_available_NO        -5.8724        nan        nan        nan         nan         nan
3D_available_YES       -6.0941        nan        nan        nan         nan         nan
Genre_Action           -3.1045        nan        nan        nan         nan         nan
Genre_Comedy           -3.0682        nan        nan        nan         nan         nan
Genre_Drama            -3.0825        nan        nan        nan         nan         nan
Genre_Thriller         -2.7113        nan        nan        nan         nan         nan
MPAA_film_rating_PG   -11.9665        nan        nan        nan         nan         nan
=======================================================================================
"""

In [137]:
# performing predictions on the test dataset
# The predict() function is useful for performing predictions. The predictions obtained are fractional values
# (between 0 and 1) which denote the probability of getting admitted. These values are hence rounded, to obtain 
# the discrete values of 1 or 0. 

In [139]:
x_prob=cls_rgs.predict_proba(x) #predict the probabality of x

In [142]:
x_prob

array([[3.39579696e-01, 6.60420304e-01],
       [3.91729808e-01, 6.08270192e-01],
       [9.99999953e-01, 4.65501638e-08],
       ...,
       [3.80047768e-01, 6.19952232e-01],
       [5.48492598e-01, 4.51507402e-01],
       [2.45552934e-01, 7.54447066e-01]])

In [143]:
y_pred=cls_rgs.predict(x) #predicted values

In [144]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,

In [145]:
# Using Confusion Matrix to find the Accuracy of the model

In [146]:
from sklearn.metrics import confusion_matrix

In [147]:
confusion_matrix(y,y_pred)

array([[182,  94],
       [103, 127]], dtype=int64)

In [148]:
#Linear Discriminant Analysis
#Supervised learning algorithm for classification tasks

In [149]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [151]:
cls_lda=LinearDiscriminantAnalysis() # Create classification object

In [152]:
cls_lda.fit(x,y)

LinearDiscriminantAnalysis()

In [153]:
y_pred_la=cls_lda.predict(x)

In [154]:
y_pred_la

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [155]:
# Using Confusion Matrix to find the Accuracy of the model

In [156]:
confusion_matrix(y,y_pred_la)

array([[191,  85],
       [ 88, 142]], dtype=int64)